<?xml version="1.0"?>
<package format="3">
  <name>ugv_auto_drive</name>
  <version>0.0.0</version>
  <description>Simple auto drive test node</description>
  <maintainer email="dudu@todo.todo">dudu</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
